version: "3"
services:
  simple-python:
      build: ./simple-python
      volumes:
        - ./simple-python:/usr/src/app
      ports:
        - 20030:80

  website:
     image: php:apache
     volumes:
        - ./website:/var/www/html
     ports:
        - 20040:80
     depends_on:
        - simple-python

